In [2]:
from sklearn.linear_model import LinearRegression
import pandas as pd
import seaborn as sns

In [21]:
dataTest = pd.read_csv('data/testData.csv')
dataTrain = pd.read_csv('data/trainData.csv')
dataTest.head()

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,...,x21,x22,x23,x24,x25,x26,x27,x28,x29,x30
0,0,68,94,34,56,15,40,89,6,44,...,7,93,22,26,99,35,15,48,51,93
1,17,94,31,75,6,15,44,74,40,38,...,83,46,57,65,87,76,42,39,87,17
2,6,15,18,85,18,90,46,52,54,60,...,9,11,31,31,64,55,14,55,28,97
3,93,62,17,60,65,36,9,75,19,92,...,6,83,31,99,90,27,43,14,12,61
4,41,48,91,60,54,56,51,85,66,25,...,67,6,43,13,37,44,18,68,5,95

In [32]:
dataTrain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x1      500 non-null    int64
 1   x2      500 non-null    int64
 2   x3      500 non-null    int64
 3   x4      500 non-null    int64
 4   x5      500 non-null    int64
 5   x6      500 non-null    int64
 6   x7      500 non-null    int64
 7   x8      500 non-null    int64
 8   x9      500 non-null    int64
 9   x10     500 non-null    int64
 10  x11     500 non-null    int64
 11  x12     500 non-null    int64
 12  x13     500 non-null    int64
 13  x14     500 non-null    int64
 14  x15     500 non-null    int64
 15  x16     500 non-null    int64
 16  x17     500 non-null    int64
 17  x18     500 non-null    int64
 18  x19     500 non-null    int64
 19  x20     500 non-null    int64
 20  x21     500 non-null    int64
 21  x22     500 non-null    int64
 22  x23     500 non-null    int64
 23  x24     500 non-null    int64
 24  x25     500 non-null    int64
 25  x26     500 non-null    int64
 26  x27     500 non-null    int64
 27  x28     500 non-null    int64
 28  x29     500 non-null    int64
 29  x30     500 non-null    int64
 30  y       500 non-null    int64
dtypes: int64(31)
memory usage: 121.2 KB

In [33]:
dataTrain.describe()

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,...,x22,x23,x24,x25,x26,x27,x28,x29,x30,y
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,...,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,48.824000,51.340000,52.342000,49.360000,49.064000,48.786000,51.490000,50.880000,49.074000,51.096000,...,49.290000,48.512000,51.012000,52.396000,50.668000,50.746000,52.080000,51.472000,50.666000,7583.158000
std,29.741387,29.199548,27.995294,27.721749,29.187321,28.946295,29.221185,29.356519,28.892457,29.621912,...,28.655334,27.874214,29.612999,28.777621,29.324967,28.920274,28.633431,29.671637,29.897595,1213.613596
min,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4679.000000
25%,22.750000,24.750000,29.000000,27.750000,24.000000,24.750000,26.000000,25.000000,23.750000,25.000000,...,25.000000,26.000000,25.000000,29.000000,25.000000,26.750000,27.750000,25.000000,25.000000,6713.500000
50%,50.000000,53.500000,52.500000,49.000000,48.500000,47.000000,54.000000,50.500000,48.000000,49.500000,...,49.000000,48.000000,50.000000,51.000000,51.000000,50.000000,53.000000,51.000000,50.000000,7553.000000
75%,74.250000,76.250000,76.000000,73.000000,76.000000,73.000000,78.000000,77.000000,74.000000,78.000000,...,74.000000,71.000000,78.000000,79.000000,77.000000,77.000000,77.000000,78.250000,79.000000,8354.000000
max,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,11421.000000

In [68]:
lm = LinearRegression()
feature_cols = dataTrain.columns[:-1]
x = dataTrain[feature_cols]
y = dataTrain['y']
lm.fit(x, y)
lm.predict(dataTest)

array([8014.85489237, 8128.45874493, 7436.93100462, 8299.26549854,
       7813.01300094, 8024.94267765, 7762.66670971, 8306.1437039 ,
       8455.11054428, 7434.03476928, 8030.50126955, 7306.03470476,
       7057.25894442, 7682.73640196, 7299.15956267, 7869.37182054,
       7368.25027964, 7936.03756225, 8783.23361559, 7145.79781467,
       7062.9161042 , 7286.42845826, 6706.2237827 , 5913.45921566,
       6764.94157067, 7465.60341417, 7015.49250605, 7288.35628597,
       6485.93656009, 8127.72191208, 7282.07116182, 8504.43327929,
       6150.92303347, 7025.71100218, 9311.31453291, 9313.02296275,
       6674.20359937, 7741.36655635, 7315.79443748, 7424.69584372,
       7091.15154007, 7850.82670727, 7477.61951863, 8439.99848135,
       5732.32869994, 8436.26789463, 7430.68322141, 9127.83786321,
       7029.0173441 , 7067.34323593, 6418.41544923, 7454.18238473,
       6545.10983253, 6420.42790074, 6400.66081897, 8114.47063464,
       8893.70693814, 8079.44250131, 7854.49522145, 7684.12420937,
       7055.95565223, 7551.82706938, 7533.26173647, 6944.57655855,
       7431.24663562, 8039.56396361, 7399.11072671, 7593.73797331,
       8586.90699813, 7764.13937693, 7964.2860611 , 6352.6389922 ,
       8298.31050771, 7632.58293035, 7941.60497358, 7910.74044716,
       6973.9700822 , 7682.69948824, 7049.47078932, 6652.17814991,
       5270.62454764, 8346.74131713, 8707.16670548, 7030.51333712,
       7864.13782113, 8552.54470655, 8555.64662541, 6853.76639   ,
       7776.81070366, 8256.92213675, 9348.34670868, 6515.43663999,
       6846.78635217, 7994.23471109, 7896.84699531, 6529.0973164 ,
       8480.51383846, 7273.5423943 , 7526.17627812, 7254.97270638,
       8186.90387126, 6811.2000312 , 9022.77140919, 7019.67189907,
       7713.73422624, 6362.76844424, 7387.75784021, 7227.59655247,
       7941.53427308, 7834.75971957, 6161.64001883, 7268.91849498,
       7797.34402814, 7826.57635543, 6982.84485428, 7573.03503309,
       8210.17516053, 8316.87578241, 8576.4122966 , 8326.72338054,
       7352.17898196, 8693.0648003 , 6636.72814582, 6205.99617857,
       8610.60632814, 7506.46870606, 8341.85280332, 8463.47361868,
       7854.17365757, 8107.27330211, 7765.49578595, 6349.44746231,
       7983.58926342, 7382.85774463, 7119.90786834, 6702.6672281 ,
       6313.17085221, 6534.23818318, 7719.23190192, 7839.98978684,
       6602.87731034, 8073.49232611, 5192.21786761, 6882.3197741 ,
       7722.20602814, 8422.63704764, 7309.24996946, 6778.05317333,
       8714.41966764, 6580.7027609 , 8601.0073133 , 7356.59246045,
       6829.42480034, 7875.91043827, 6633.75020381, 9008.20565639,
       6526.42482939, 6510.06266154, 9203.31361184, 7200.49743571,
       7832.82516003, 8363.3020109 , 7511.69988547, 6776.88130766,
       6990.13169538, 7514.11978563, 6920.21026412, 9465.89899301,
       7069.65806503, 7028.96787981, 9843.19235206, 8125.86899105,
       6831.36541629, 7139.33947899, 7073.92330208, 8865.69752707,
       8455.04646777, 8204.08307621, 7844.95232555, 6402.85300237,
       7486.77894541, 7807.44827254, 7412.94035772, 6668.63783549,
       6653.86066992, 7049.96183362, 7055.1044137 , 8634.03357217,
       8429.70954569, 8370.76517785, 7222.81752778, 6481.83623309,
       7324.27565622, 6834.26473016, 7691.50938614, 7146.15202684,
       8914.95550363, 8263.25215191, 8715.48425414, 7671.95618239,
       8286.0374763 , 6739.03135244, 6355.41507341, 6884.53036144,
       8150.45555628, 7087.75645769, 8157.10167503, 8082.15029019,
       6049.94855134, 8277.40796934, 6981.57884307, 9189.27330062,
       6931.31538988, 8125.2963167 , 8401.51514672, 8099.52071296,
       7206.48231451, 7412.1027224 , 6859.87532111, 7950.06178415,
       6874.88322225, 6904.28662545, 7076.17287377, 7347.72403754,
       8344.58117087, 6666.26514958, 8487.98466008, 8318.34571965,
       6951.28271281, 7673.22205378, 7001.41742165, 8193.62886762,
       8861.88132082, 7644.73155804, 8143.8519951 , 7629.71535544,
       8544.47589318, 7663.55566052, 6758.23460438, 8084.47980409,
       8087.57797482, 7434.98577555, 8131.42516274, 7877.2247601 ,
       8859.5051293 , 8665.2540814 , 7436.55488486, 7625.6294083 ,
       7225.75002421, 6055.69490901, 8078.32445698, 6135.81973255,
       6246.65119883, 5590.52583447, 8156.24753957, 7277.50906099,
       5967.05661077, 7952.43557386, 6063.28893237, 8158.12138056,
       8386.76062509, 7911.57339804, 6915.68593993, 7014.3035582 ,
       9486.57192429, 6637.71296437, 6895.93876104, 9225.9518372 ,
       7183.54864039, 6840.68088698, 7043.62650186, 7928.95309888,
       7014.45070553, 7386.09643537, 8698.8552757 , 7874.64805344,
       6590.95149182, 7524.50151402, 6686.51778868, 8304.76030344,
       6864.94607325, 8488.49764702, 8709.73840461, 6596.16580226,
       8323.82010919, 7636.01559289, 7357.65739752, 7887.97496981,
       9405.69982713, 7261.8715634 , 9018.68483989, 8620.09925192,
       7536.19443736, 9153.60421704, 8409.16255345, 7002.29570934,
       7563.5938211 , 6883.78700358, 6865.3165043 , 7426.4232004 ,
       8780.48145727, 6757.81011416, 7387.23801309, 8161.83342338,
       7722.81401751, 7321.33276268, 8743.15848778, 7977.05710759,
       7346.43053373, 6077.28540503, 7356.23033944, 7517.16843916,
       6918.71495876, 7244.01359904, 7879.38786503, 8733.57443633,
       7479.14613392, 6758.7788162 , 7867.67249105, 7239.49480893,
       7409.07704654, 7517.96543108, 8265.07811403, 7602.85126967,
       7647.66886865, 6772.18168983, 6786.78591967, 6902.56889685,
       6158.17666127, 6569.64583508, 5799.83552757, 6955.85635393,
       8081.85161766, 5691.98098971, 7730.49887541, 8232.40661118,
       8489.70243753, 7644.88495144, 7386.30456395, 7719.43507861,
       7525.14490913, 7394.35881357, 7423.24557034, 8133.07753836,
       7033.94454042, 7009.04566548, 7107.26294107, 7541.97765024,
       7874.94438132, 9005.33785485, 6514.41626148, 6098.65795459,
       8121.41038087, 8293.18173441, 6909.75388186, 7183.18409054,
       6945.93187176, 8695.48704234, 8436.12942834, 7732.23610903,
       9060.55836228, 8548.95687831, 7142.42823077, 7805.08613954,
       7758.32795521, 6281.10570711, 6714.65362465, 7656.71932555,
       7289.19793179, 6872.73996254, 6820.94430957, 7153.45028892,
       7673.94676052, 6810.11313127, 9150.70760321, 7831.71017783,
       8131.99747003, 7728.66838404, 6639.47741403, 8703.24545967,
       7145.22267479, 6790.05721542, 8642.09060872, 7380.60891957,
       8190.52025776, 7079.59730493, 8036.78285259, 7548.08680605,
       7048.52203765, 6735.09774672, 7723.51738168, 8051.9355245 ,
       7501.31598861, 8200.24782622, 6131.69219573, 5769.84452615,
       6946.21101877, 9401.82603677, 7233.33796534, 6314.5382333 ,
       7444.78425455, 7945.44457804, 6366.98864542, 5731.72752092,
       7351.85587096, 7471.26078698, 7266.40835767, 6956.48446577,
       6779.00246962, 6485.30246633, 7604.91405389, 7510.52840312,
       6551.63018054, 7000.67454989, 8107.54118896, 7049.20727682,
       7155.79730606, 9552.00565294, 5385.40630115, 7099.03438293,
       9369.69961016, 8267.82176792, 6681.18994947, 7499.95931601,
       7350.1869827 , 6645.87905467, 7122.54608122, 8158.87295135,
       7367.99179118, 7244.16874588, 8390.36486059, 7161.72352796,
       8019.71063455, 6871.57087363, 7424.41722575, 7529.11067493,
       6937.9708975 , 7613.69797096, 7147.24333439, 6588.11207723,
       7674.77995221, 7670.62681422, 6653.57355787, 8160.45206689,
       6330.72463922, 6870.03280221, 7888.53353567, 7860.99520321,
       6805.47081602, 8609.7290793 , 6836.05827305, 7496.58758261,
       6957.30892465, 7802.56827884, 8420.88961254, 7760.97835776,
       7792.28379804, 9192.19589829, 7170.39013225, 7887.18586153,
       7847.64286776, 7675.39476133, 7810.1319045 , 6933.01154957,
       8681.06436819, 7780.29051317, 6445.03800638, 6791.51679254,
       7078.0032962 , 8168.01400261, 8204.05371545, 6724.12460375,
       7444.79156605, 8433.9527254 , 7992.16798807, 7271.87883454,
       6867.47315883, 8249.00444639, 9153.8596945 , 8251.72434756,
       7472.31642971, 7940.34277651, 7116.83665435, 7943.91710144,
       6301.87142505, 7272.98512335, 6260.87521393, 7544.89833496,
       7105.04867956, 7443.7013577 , 5896.28514204, 7475.5708421 ,
       8466.33595841, 7634.37231227, 7493.96900858, 8279.77843558,
       9018.63589817, 7436.95606528, 7422.01391497, 7694.76441114])